FROM python:3.11-slim

WORKDIR /app

COPY requirements.balance_service.txt .
RUN pip install --no-cache-dir -r requirements.balance_service.txt

COPY . .

# Comando para ejecutar el servicio Flask
CMD ["python", "app/balance_service.py"]